APPS+=powertrace
DEFINES=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI = ../../..

all: example-abc example-mesh example-collect example-trickle example-polite \
     example-rudolph0 example-rudolph1 example-rudolph2 example-rucb \
     example-runicast example-unicast example-neighbors hello-world hello-world-micaz

CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
